# Generated by Django 4.2.11 on 2024-09-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0007_move_router"),
        ("peering", "0103_session_bfd"),
    ]

    operations = []
